//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinapsisGEO.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinapsisEntities : DbContext
    {
        public SinapsisEntities()
            : base("name=SinapsisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tel_Clientes> tel_Clientes { get; set; }
        public DbSet<tel_Pedidos> tel_Pedidos { get; set; }
        public DbSet<tel_Sucursal> tel_Sucursal { get; set; }
    }
}
