//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinapsisGEO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Sucursal
    {
        public tel_Sucursal()
        {
            this.tel_Pedidos = new HashSet<tel_Pedidos>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public string Sucursal { get; set; }
        public string Obs { get; set; }
        public string IdLista { get; set; }
    
        public virtual ICollection<tel_Pedidos> tel_Pedidos { get; set; }
    }
}
