//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinapsisGEO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Clientes
    {
        public tel_Clientes()
        {
            this.tel_Pedidos = new HashSet<tel_Pedidos>();
        }
    
        public int IdCliente { get; set; }
        public int IdEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Direccion1 { get; set; }
        public string Direccion { get; set; }
        public string Empresa { get; set; }
        public string referencia { get; set; }
        public string audit_Usuario { get; set; }
        public Nullable<System.DateTime> Audit_Fecha { get; set; }
        public string obs { get; set; }
        public string NroDoc { get; set; }
        public Nullable<long> Telefono { get; set; }
        public Nullable<short> NroCasa { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string cuadrante { get; set; }
        public string Nombres { get; set; }
        public Nullable<int> IdClienteWeb { get; set; }
        public Nullable<decimal> GeoLat { get; set; }
        public Nullable<decimal> GeoLng { get; set; }
    
        public virtual ICollection<tel_Pedidos> tel_Pedidos { get; set; }
    }
}
