//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Reportes
    {
        public int IdReporte { get; set; }
        public Nullable<int> IdObjeto { get; set; }
        public string Nombre { get; set; }
        public string Archivo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Disponible { get; set; }
        public byte[] Image { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tipo { get; set; }
        public string Script { get; set; }
        public string Script2 { get; set; }
        public byte[] Script3 { get; set; }
    }
}
