//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_ReportesGEO
    {
        public int IdReporte { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Descripcion { get; set; }
        public string Nombre { get; set; }
        public string script { get; set; }
        public string Script2 { get; set; }
    }
}
