//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Menu
    {
        public sys_Menu()
        {
            this.sys_MenuDet = new HashSet<sys_MenuDet>();
        }
    
        public int IdMenu { get; set; }
        public string Nombre { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> IdPadre { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Orden { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        public virtual ICollection<sys_MenuDet> sys_MenuDet { get; set; }
    }
}
