//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_MenuDet
    {
        public int Id { get; set; }
        public Nullable<int> IdMenu { get; set; }
        public string IdFamilia { get; set; }
        public string IdLinea { get; set; }
        public string IdGrupo { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual sys_Menu sys_Menu { get; set; }
    }
}
