//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_FormaPago
    {
        public tel_FormaPago()
        {
            this.tel_Carrito = new HashSet<tel_Carrito>();
            this.tel_Pedidos = new HashSet<tel_Pedidos>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdFormaPago { get; set; }
        public string FormaPago { get; set; }
    
        public virtual ICollection<tel_Carrito> tel_Carrito { get; set; }
        public virtual ICollection<tel_Pedidos> tel_Pedidos { get; set; }
    }
}
