//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Comentarios
    {
        public int IdComentario { get; set; }
        public int IdEmpresa { get; set; }
        public int IdCliente { get; set; }
        public string Comentario { get; set; }
        public string audit_Usuario { get; set; }
        public Nullable<System.DateTime> Audit_Fecha { get; set; }
        public string IdTipoReclamo { get; set; }
        public Nullable<int> IdPedido { get; set; }
        public Nullable<bool> Visto { get; set; }
        public string visto_Usuario { get; set; }
        public Nullable<System.DateTime> Visto_Fecha { get; set; }
        public Nullable<long> Telefono { get; set; }
    
        public virtual tel_TipoReclamo tel_TipoReclamo { get; set; }
    }
}
