//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_PedidosDet
    {
        public tel_PedidosDet()
        {
            this.tel_PedidosDet1 = new HashSet<tel_PedidosDet>();
            this.tel_PedidosDet11 = new HashSet<tel_PedidosDet>();
        }
    
        public int IdPedidoDet { get; set; }
        public Nullable<int> IdPedido { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string IdProducto { get; set; }
        public string IdProducto1 { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Obs { get; set; }
        public string obs1 { get; set; }
        public Nullable<int> IdPDPadre { get; set; }
    
        public virtual tel_Pedidos tel_Pedidos { get; set; }
        public virtual ICollection<tel_PedidosDet> tel_PedidosDet1 { get; set; }
        public virtual tel_PedidosDet tel_PedidosDet2 { get; set; }
        public virtual ICollection<tel_PedidosDet> tel_PedidosDet11 { get; set; }
        public virtual tel_PedidosDet tel_PedidosDet3 { get; set; }
        public virtual tel_Productos tel_Productos { get; set; }
    }
}
