//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Insumos
    {
        public tel_Insumos()
        {
            this.tel_Faltantes = new HashSet<tel_Faltantes>();
        }
    
        public int IdInsumo { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<tel_Faltantes> tel_Faltantes { get; set; }
    }
}
