//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Clientes
    {
        public tel_Clientes()
        {
            this.tel_Carrito = new HashSet<tel_Carrito>();
            this.tel_Pedidos = new HashSet<tel_Pedidos>();
            this.Tel_Direcciones = new HashSet<Tel_Direcciones>();
        }
    
        public int IdCliente { get; set; }
        public int IdEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Direccion1 { get; set; }
        public string Direccion { get; set; }
        public string Empresa { get; set; }
        public string referencia { get; set; }
        public string audit_Usuario { get; set; }
        public Nullable<System.DateTime> Audit_Fecha { get; set; }
        public string obs { get; set; }
        public string NroDoc { get; set; }
        public Nullable<long> Telefono { get; set; }
        public Nullable<short> NroCasa { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string cuadrante { get; set; }
        public string Nombres { get; set; }
        public Nullable<int> IdClienteWeb { get; set; }
        public Nullable<decimal> GeoLat { get; set; }
        public Nullable<decimal> GeoLng { get; set; }
        public string RUC { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string IdTipo { get; set; }
        public Nullable<bool> Diplomatico { get; set; }
        public Nullable<int> IdClienteWeb1 { get; set; }
        public string Telefonoweb { get; set; }
        public Nullable<bool> Verificado { get; set; }
    
        public virtual ICollection<tel_Carrito> tel_Carrito { get; set; }
        public virtual ICollection<tel_Pedidos> tel_Pedidos { get; set; }
        public virtual ICollection<Tel_Direcciones> Tel_Direcciones { get; set; }
        public virtual tel_TipoCliente tel_TipoCliente { get; set; }
    }
}
