//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_ListaPrecio
    {
        public tel_ListaPrecio()
        {
            this.tel_Precios = new HashSet<tel_Precios>();
        }
    
        public int IdEmpresa { get; set; }
        public string IdLista { get; set; }
        public string Lista { get; set; }
    
        public virtual ICollection<tel_Precios> tel_Precios { get; set; }
    }
}
