//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Opciones
    {
        public tel_Opciones()
        {
            this.tel_OpcionesDet = new HashSet<tel_OpcionesDet>();
            this.tel_ProductoOpcion = new HashSet<tel_ProductoOpcion>();
        }
    
        public int IdOpcion { get; set; }
        public string Titulo { get; set; }
        public string TipoControl { get; set; }
        public string Seleccion { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string IdFamilia { get; set; }
        public string IdLinea { get; set; }
        public string IdGrupo { get; set; }
        public Nullable<int> Maximo { get; set; }
        public Nullable<bool> PermiteMitad { get; set; }
        public Nullable<bool> EsCombo { get; set; }
        public string IdProducto { get; set; }
    
        public virtual ICollection<tel_OpcionesDet> tel_OpcionesDet { get; set; }
        public virtual ICollection<tel_ProductoOpcion> tel_ProductoOpcion { get; set; }
    }
}
