//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Carrito
    {
        public tel_Carrito()
        {
            this.tel_Carrito_Item = new HashSet<tel_Carrito_Item>();
        }
    
        public int IdCarrito { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> NroPedido { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Estado { get; set; }
        public Nullable<long> Telefono { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public string Empresa { get; set; }
        public string referencia { get; set; }
        public Nullable<int> audit_Usuario { get; set; }
        public Nullable<System.DateTime> Audit_Fecha { get; set; }
        public string obs { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string cuadrante { get; set; }
        public string IdTipoPedido { get; set; }
        public Nullable<decimal> CostoEnvio { get; set; }
        public Nullable<decimal> TotalPedido { get; set; }
        public Nullable<decimal> TotalGeneral { get; set; }
        public string UserName { get; set; }
        public string Anulado { get; set; }
        public Nullable<int> IdFormaPago { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public string ProgramarEnvio { get; set; }
        public Nullable<decimal> Vuelto { get; set; }
        public Nullable<bool> TransferTemporal { get; set; }
        public Nullable<int> IdPedidoOrigen { get; set; }
    
        public virtual ICollection<tel_Carrito_Item> tel_Carrito_Item { get; set; }
        public virtual tel_Clientes tel_Clientes { get; set; }
        public virtual Tel_Direcciones Tel_Direcciones { get; set; }
        public virtual tel_FormaPago tel_FormaPago { get; set; }
    }
}
