//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Avisos
    {
        public int idAviso { get; set; }
        public int idEmpresa { get; set; }
        public string Titulo { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> AuditFecha { get; set; }
    }
}
