//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_CombosDet
    {
        public int IdCD { get; set; }
        public Nullable<int> IdCombo { get; set; }
        public string IdProducto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<bool> Predet { get; set; }
    
        public virtual tel_Combos tel_Combos { get; set; }
        public virtual tel_Productos tel_Productos { get; set; }
    }
}
