//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Sucursal
    {
        public tel_Sucursal()
        {
            this.tel_Pedidos = new HashSet<tel_Pedidos>();
            this.tel_Moviles = new HashSet<tel_Moviles>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public string Sucursal { get; set; }
        public string Obs { get; set; }
        public string IdLista { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Geo { get; set; }
        public Nullable<int> CantViviendas { get; set; }
        public Nullable<int> TiempoServicio { get; set; }
    
        public virtual ICollection<tel_Pedidos> tel_Pedidos { get; set; }
        public virtual tel_Empresa tel_Empresa { get; set; }
        public virtual ICollection<tel_Moviles> tel_Moviles { get; set; }
    }
}
