//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_OpcionesDet
    {
        public int IdOD { get; set; }
        public Nullable<int> IdOpcion { get; set; }
        public string Titulo { get; set; }
        public Nullable<decimal> ValorAdicional { get; set; }
        public string IdProducto { get; set; }
        public Nullable<bool> Predet { get; set; }
    
        public virtual tel_Opciones tel_Opciones { get; set; }
    }
}
