//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_TipoCliente
    {
        public tel_TipoCliente()
        {
            this.tel_Clientes = new HashSet<tel_Clientes>();
        }
    
        public int IdEmpresa { get; set; }
        public string IdTipo { get; set; }
        public string TipoCliente { get; set; }
    
        public virtual ICollection<tel_Clientes> tel_Clientes { get; set; }
    }
}
