//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Combos
    {
        public tel_Combos()
        {
            this.tel_CombosDet = new HashSet<tel_CombosDet>();
        }
    
        public int IdCombo { get; set; }
        public string IdProducto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> PermiteMitad { get; set; }
    
        public virtual tel_Productos tel_Productos { get; set; }
        public virtual ICollection<tel_CombosDet> tel_CombosDet { get; set; }
    }
}
