//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Linea
    {
        public tel_Linea()
        {
            this.tel_Grupo = new HashSet<tel_Grupo>();
            this.tel_Productos = new HashSet<tel_Productos>();
        }
    
        public int IdEmpresa { get; set; }
        public string IdFamilia { get; set; }
        public string IdLinea { get; set; }
        public string Linea { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual tel_Familia tel_Familia { get; set; }
        public virtual ICollection<tel_Grupo> tel_Grupo { get; set; }
        public virtual ICollection<tel_Productos> tel_Productos { get; set; }
    }
}
