//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_MovilTracker
    {
        public int IdTrack { get; set; }
        public int IdEmpresa { get; set; }
        public int IdMovil { get; set; }
        public string Operacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string HostIP { get; set; }
        public string HostName { get; set; }
        public Nullable<System.DateTime> AuditFecha { get; set; }
    
        public virtual tel_Moviles tel_Moviles { get; set; }
    }
}
