//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Precios
    {
        public int IdPrecio { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string IdProducto { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string IdLista { get; set; }
    
        public virtual tel_Productos tel_Productos { get; set; }
        public virtual tel_ListaPrecio tel_ListaPrecio { get; set; }
    }
}
