//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Grupo
    {
        public int IdEmpresa { get; set; }
        public string IdFamilia { get; set; }
        public string IdLinea { get; set; }
        public string IdGrupo { get; set; }
        public string Grupo { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual tel_Linea tel_Linea { get; set; }
    }
}
