//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Empresa
    {
        public tel_Empresa()
        {
            this.tel_Pedidos = new HashSet<tel_Pedidos>();
            this.tel_Sucursal = new HashSet<tel_Sucursal>();
        }
    
        public int IdEmpresa { get; set; }
        public string Empresa { get; set; }
        public string Direccion { get; set; }
        public string Telefonos { get; set; }
        public string Contacto { get; set; }
        public Nullable<decimal> CostoEnvio { get; set; }
    
        public virtual ICollection<tel_Pedidos> tel_Pedidos { get; set; }
        public virtual ICollection<tel_Sucursal> tel_Sucursal { get; set; }
    }
}
