//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tel_Carrito_Item
    {
        public tel_Carrito_Item()
        {
            this.tel_Carrito_Item1 = new HashSet<tel_Carrito_Item>();
        }
    
        public int IdCarritoItem { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string IdProducto { get; set; }
        public string IdProducto1 { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> IdCarrito { get; set; }
        public string Obs { get; set; }
        public Nullable<int> IdCIPadre { get; set; }
    
        public virtual tel_Carrito tel_Carrito { get; set; }
        public virtual tel_Productos tel_Productos { get; set; }
        public virtual ICollection<tel_Carrito_Item> tel_Carrito_Item1 { get; set; }
        public virtual tel_Carrito_Item tel_Carrito_Item2 { get; set; }
    }
}
