//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tel_Direcciones
    {
        public Tel_Direcciones()
        {
            this.tel_Carrito = new HashSet<tel_Carrito>();
        }
    
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string Direccion1 { get; set; }
        public string Direccion { get; set; }
        public string referencia { get; set; }
        public Nullable<short> NroCasa { get; set; }
        public string cuadrante { get; set; }
        public Nullable<System.DateTime> Audit_Fecha { get; set; }
        public string Audit_Usuario { get; set; }
        public Nullable<decimal> GeoLat { get; set; }
        public Nullable<decimal> GeoLng { get; set; }
        public Nullable<int> IdDir1 { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public int Id { get; set; }
        public Nullable<bool> Principal { get; set; }
        public Nullable<int> IdBarrio { get; set; }
        public Nullable<int> IdDir2 { get; set; }
    
        public virtual tel_Clientes tel_Clientes { get; set; }
        public virtual ICollection<tel_Carrito> tel_Carrito { get; set; }
        public virtual tel_Barrios tel_Barrios { get; set; }
        public virtual tel_Ciudades tel_Ciudades { get; set; }
    }
}
