//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coord
    {
        public string Cuadrante { get; set; }
        public string Coordenadas { get; set; }
        public string Column_2 { get; set; }
        public string Column_3 { get; set; }
        public string Column_4 { get; set; }
        public string Column_5 { get; set; }
        public string Column_6 { get; set; }
        public string Column_7 { get; set; }
        public string Column_8 { get; set; }
        public string Column_9 { get; set; }
        public string Column_10 { get; set; }
        public string Column_11 { get; set; }
        public string Column_12 { get; set; }
        public string Column_13 { get; set; }
        public string Column_14 { get; set; }
        public string Column_15 { get; set; }
        public string Column_16 { get; set; }
        public string Column_17 { get; set; }
        public string Column_18 { get; set; }
        public string Column_19 { get; set; }
        public string Column_20 { get; set; }
        public string Column_21 { get; set; }
        public string Column_22 { get; set; }
        public string Column_23 { get; set; }
        public string Column_24 { get; set; }
        public string Column_25 { get; set; }
        public string Column_26 { get; set; }
        public string Column_27 { get; set; }
        public string Column_28 { get; set; }
        public string Column_29 { get; set; }
        public string Column_30 { get; set; }
        public string Column_31 { get; set; }
        public string Column_32 { get; set; }
        public string Column_33 { get; set; }
        public string Column_34 { get; set; }
        public string Column_35 { get; set; }
        public string Column_36 { get; set; }
        public string Column_37 { get; set; }
        public string Column_38 { get; set; }
        public string Column_39 { get; set; }
        public string Column_40 { get; set; }
        public string Column_41 { get; set; }
        public string Column_42 { get; set; }
        public string Column_43 { get; set; }
        public string Column_44 { get; set; }
        public string Column_45 { get; set; }
        public string Column_46 { get; set; }
        public string Column_47 { get; set; }
        public string Column_48 { get; set; }
        public string Column_49 { get; set; }
        public string Column_50 { get; set; }
        public string Column_51 { get; set; }
        public string Column_52 { get; set; }
        public string Column_53 { get; set; }
        public string Column_54 { get; set; }
        public string Column_55 { get; set; }
        public string Column_56 { get; set; }
        public string Column_57 { get; set; }
        public string Column_58 { get; set; }
        public string Column_59 { get; set; }
        public string Column_60 { get; set; }
        public string Column_61 { get; set; }
        public string Column_62 { get; set; }
        public string Column_63 { get; set; }
        public string Column_64 { get; set; }
        public string Column_65 { get; set; }
    }
}
