//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class gis_Cuadrantes
    {
        public int IdCuadrante { get; set; }
        public Nullable<int> IdCalle { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> dNro { get; set; }
        public Nullable<int> hNro { get; set; }
        public string Cuadrante { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual gis_calles gis_calles { get; set; }
    }
}
