//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class PHEntities : DbContext
    {
        public PHEntities()
            : base("name=PHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SP_COMANDA> SP_COMANDA { get; set; }
        public DbSet<SP_ESTADO> SP_ESTADO { get; set; }
    
        public virtual ObjectResult<SP_COMANDA> SP_GG_COMANDA_ADD(Nullable<int> iDSUCURSAL, string hEADER, string dETAILS, string cLIENTE, Nullable<int> iDPEDIDO)
        {
            var iDSUCURSALParameter = iDSUCURSAL.HasValue ?
                new ObjectParameter("IDSUCURSAL", iDSUCURSAL) :
                new ObjectParameter("IDSUCURSAL", typeof(int));
    
            var hEADERParameter = hEADER != null ?
                new ObjectParameter("HEADER", hEADER) :
                new ObjectParameter("HEADER", typeof(string));
    
            var dETAILSParameter = dETAILS != null ?
                new ObjectParameter("DETAILS", dETAILS) :
                new ObjectParameter("DETAILS", typeof(string));
    
            var cLIENTEParameter = cLIENTE != null ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(string));
    
            var iDPEDIDOParameter = iDPEDIDO.HasValue ?
                new ObjectParameter("IDPEDIDO", iDPEDIDO) :
                new ObjectParameter("IDPEDIDO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_COMANDA>("SP_GG_COMANDA_ADD", iDSUCURSALParameter, hEADERParameter, dETAILSParameter, cLIENTEParameter, iDPEDIDOParameter);
        }
    
        public virtual ObjectResult<SP_COMANDA> SP_GG_COMANDA_ADD(Nullable<int> iDSUCURSAL, string hEADER, string dETAILS, string cLIENTE, Nullable<int> iDPEDIDO, MergeOption mergeOption)
        {
            var iDSUCURSALParameter = iDSUCURSAL.HasValue ?
                new ObjectParameter("IDSUCURSAL", iDSUCURSAL) :
                new ObjectParameter("IDSUCURSAL", typeof(int));
    
            var hEADERParameter = hEADER != null ?
                new ObjectParameter("HEADER", hEADER) :
                new ObjectParameter("HEADER", typeof(string));
    
            var dETAILSParameter = dETAILS != null ?
                new ObjectParameter("DETAILS", dETAILS) :
                new ObjectParameter("DETAILS", typeof(string));
    
            var cLIENTEParameter = cLIENTE != null ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(string));
    
            var iDPEDIDOParameter = iDPEDIDO.HasValue ?
                new ObjectParameter("IDPEDIDO", iDPEDIDO) :
                new ObjectParameter("IDPEDIDO", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_COMANDA>("SP_GG_COMANDA_ADD_EH", mergeOption, iDSUCURSALParameter, hEADERParameter, dETAILSParameter, cLIENTEParameter, iDPEDIDOParameter);
        }
    
        public virtual ObjectResult<SP_ESTADO> SP_XGG_ESTADO(Nullable<int> iDPEDIDO)
        {
            var iDPEDIDOParameter = iDPEDIDO.HasValue ?
                new ObjectParameter("IDPEDIDO", iDPEDIDO) :
                new ObjectParameter("IDPEDIDO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ESTADO>("SP_XGG_ESTADO", iDPEDIDOParameter);
        }
    
        public virtual ObjectResult<SP_ESTADO> SP_XGG_ESTADO(Nullable<int> iDPEDIDO, MergeOption mergeOption)
        {
            var iDPEDIDOParameter = iDPEDIDO.HasValue ?
                new ObjectParameter("IDPEDIDO", iDPEDIDO) :
                new ObjectParameter("IDPEDIDO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ESTADO>("SP_XGG_ESTADO", mergeOption, iDPEDIDOParameter);
        }
    }
}
