//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_COMANDA
    {
        public int IDCOMANDA { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> IDDIRECCION { get; set; }
        public Nullable<int> ESTADO { get; set; }
    }

   


}
