//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.SWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SWS.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Operacion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarMovil", ReplyAction="*")]
        Tracker.SWS.ActualizarMovilResponse ActualizarMovil(Tracker.SWS.ActualizarMovilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarMovil", ReplyAction="*")]
        System.Threading.Tasks.Task<Tracker.SWS.ActualizarMovilResponse> ActualizarMovilAsync(Tracker.SWS.ActualizarMovilRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarMovilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarMovil", Namespace="http://tempuri.org/", Order=0)]
        public Tracker.SWS.ActualizarMovilRequestBody Body;
        
        public ActualizarMovilRequest() {
        }
        
        public ActualizarMovilRequest(Tracker.SWS.ActualizarMovilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarMovilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdMovil;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime Hora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Operacion;
        
        public ActualizarMovilRequestBody() {
        }
        
        public ActualizarMovilRequestBody(int IdMovil, System.DateTime Hora, string Operacion) {
            this.IdMovil = IdMovil;
            this.Hora = Hora;
            this.Operacion = Operacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarMovilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarMovilResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tracker.SWS.ActualizarMovilResponseBody Body;
        
        public ActualizarMovilResponse() {
        }
        
        public ActualizarMovilResponse(Tracker.SWS.ActualizarMovilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarMovilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ActualizarMovilResult;
        
        public ActualizarMovilResponseBody() {
        }
        
        public ActualizarMovilResponseBody(int ActualizarMovilResult) {
            this.ActualizarMovilResult = ActualizarMovilResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Tracker.SWS.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Tracker.SWS.WebService1Soap>, Tracker.SWS.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tracker.SWS.ActualizarMovilResponse Tracker.SWS.WebService1Soap.ActualizarMovil(Tracker.SWS.ActualizarMovilRequest request) {
            return base.Channel.ActualizarMovil(request);
        }
        
        public int ActualizarMovil(int IdMovil, System.DateTime Hora, string Operacion) {
            Tracker.SWS.ActualizarMovilRequest inValue = new Tracker.SWS.ActualizarMovilRequest();
            inValue.Body = new Tracker.SWS.ActualizarMovilRequestBody();
            inValue.Body.IdMovil = IdMovil;
            inValue.Body.Hora = Hora;
            inValue.Body.Operacion = Operacion;
            Tracker.SWS.ActualizarMovilResponse retVal = ((Tracker.SWS.WebService1Soap)(this)).ActualizarMovil(inValue);
            return retVal.Body.ActualizarMovilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tracker.SWS.ActualizarMovilResponse> Tracker.SWS.WebService1Soap.ActualizarMovilAsync(Tracker.SWS.ActualizarMovilRequest request) {
            return base.Channel.ActualizarMovilAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tracker.SWS.ActualizarMovilResponse> ActualizarMovilAsync(int IdMovil, System.DateTime Hora, string Operacion) {
            Tracker.SWS.ActualizarMovilRequest inValue = new Tracker.SWS.ActualizarMovilRequest();
            inValue.Body = new Tracker.SWS.ActualizarMovilRequestBody();
            inValue.Body.IdMovil = IdMovil;
            inValue.Body.Hora = Hora;
            inValue.Body.Operacion = Operacion;
            return ((Tracker.SWS.WebService1Soap)(this)).ActualizarMovilAsync(inValue);
        }
    }
}
